spring:
  application:
    name: Reto2
  profiles.active: dev

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never # on_param
    include-exception: false

---
spring:
  sql.init.mode: always
  config.activate.on-profile: dev
  devtools.restart.enabled: true
  datasource:
    url: "jdbc:h2:mem:reto2db"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  port: 9900

#debug: true
logging:
  path: /var/logs/
  file: /var/logs/accounts.log
  level:
    root: INFO

app.jwt.secret: SECRET-KEY-VALUE
---
spring:
  config.activate.on-profile: prod
  sql.init.mode: never
  datasource:
    url: "jdbc:mysql://localhost/reto2_db"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: reto2_user
    password: reto2
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    defer-datasource-initialization: true

server:
  servlet.contextPath: /api/v1
  port: 9943
  ssl:
    key-store: keystore.p12
    key-store-password: reto2spring
    keyStoreType: PKCS12
    keyAlias: Reto_2

#debug: true
logging:
  #path: /var/logs/
  #file: /var/logs/accounts.log
  level:
    root: ERROR